name: 'Terraform Destroy'

on:
  pull_request:
    types:
      - closed  # Trigger when a pull request is closed (merged)
    branches:
      - main    # Only trigger if the PR is merged into main

permissions:
  contents: read
  id-token: write

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -input=false

      - name: Terraform Destroy
        run: terraform destroy -input=false -auto-approve
