name: 'Terraform Destroy'

on: 
  workflow_dispatch  # Allows the workflow to be triggered manually

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
        working-directory: ./terraform  # Assuming your Terraform files are in this directory

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init  # Initialize Terraform
        run: terraform init

      - name: Terraform Plan (for destroy)  # Plan the destruction
        run: terraform plan -destroy -input=false

      - name: Terraform Destroy  # Execute the destruction
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -input=false -auto-approve
