name: Drift Detection

on:
  schedule:
    - cron: '*/45 * * * *'  # Runs every 45 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        id: init
        run: terraform init -no-color -input=false -lock=false

      - name: Validate Terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock=false -detailed-exitcode -compact-warnings
        continue-on-error: true

      - name: Output Terraform Plan Summary
        run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          ### 🤖 Terraform plan
          ```terraform
          ${{ steps.plan.outputs.stdout }}
          ```
          EOF
