name: Drift Detection

on:
  schedule:
    - cron: '*/45 * * * *'  # Runs every 45 minutes

jobs:
  drift-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'eu-west-2'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
         
      - name: Initialize Terraform
        run: terraform init -no-color -input=false -lock=false

      - name: Run Terraform Plan for Drift Detection
        run: terraform plan -no-color -lock=false -detailed-exitcode -out drift.tfplan
        continue-on-error: true

      - name: Output Plan Summary
        if: failure()
        run: |
          echo "Drift detected. Check the plan output for details."
