name: 'Drift Detection'

on:
  schedule:
    - cron: '*/45 * * * *'  # Runs every 45 minutes

jobs:
  detect_drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run reusable workflow
        uses: ./.github/workflows/plan.yml  # Reusable workflow reference
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}