name: 'Terraform Plan'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: development
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform  # Default directory for all steps
    env:
        GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false