name: 'Terraform Validate Check'

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  terraform_validate:
    name: 'Terraform Validate Check'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: terraform validate
